export const UPDATE_LOGIN_FORM = "UPDATE_LOGIN_FORM";
export const USER_LOADING = "USER_LOADING";
export const USER_DISABLE_LOADING = "USER_DISABLE_LOADING";
export const GET_USERS = "GET_USERS";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAILED = "GET_USERS_FAILED";
export const GET_EXAMS_SUCCESS = "GET_EXAMS_SUCCESS";
export const GET_EXAMS_FAILED = "GET_EXAMS_FAILED";
export const EXAM_LOADING = "EXAM_LOADING";
export const ADD_EXAMS_SUCCESS = "ADD_EXAMS_SUCCESS";
export const SET_MESSAGE = "SET_MESSAGE";
export const ADD_EXAMS_FAILED = "ADD_EXAMS_FAILED";
export const DELETE_EXAMS_SUCCESS = "DELETE_EXAMS_SUCCESS";
export const DELETE_EXAMS_FAILED = "DELETE_EXAMS_FAILED";
export const UPDATE_EXAMS_SUCCESS = "UPDATE_EXAMS_SUCCESS";
export const UPDATE_EXAMS_FAILED = "UPDATE_EXAMS_FAILED";
export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const GET_EXAMGROUP_SUCCESS = "GET_EXAMGROUP_SUCCESS";
export const GET_EXAMGROUP_FAILED = "GET_EXAMGROUP_FAILED";
export const EXAMGROUP_LOADING = "EXAMGROUP_LOADING";
export const GET_EXAMRESULTS_SUCCESS = "GET_EXAMRESULTS_SUCCESS";
export const GET_EXAMRESULTS_FAILED = "GET_EXAMRESULTS_FAILED";
export const EXAMRESULTS_LOADING = "EXAMRESULTS_LOADING";
export const GET_CHART_DATA_SUCCESS = "GET_CHART_DATA_SUCCESS";
export const GET_CHART_DATA_FAILED = "GET_CHART_DATA_FAILED";
export const GET_EXAM_ANAYTICS_MENU_LOADING = "GET_EXAM_ANAYTICS_MENU_LOADING";
export const GET_EXAM_ANAYTICS_MENU_SUCCESS = "GET_EXAM_ANAYTICS_MENU_SUCCESS";
export const GET_EXAM_ANAYTICS_MENU_FAILED = "GET_EXAM_ANAYTICS_MENU_FAILED";

export const GET_LOGANALYTICSRESULT_SUCCESS = "GET_LOGANALYTICSRESULT_SUCCESS";
export const GET_LOGANALYTICSRESULT_FAILED = "GET_LOGANALYTICSRESULT_FAILED";
export const LOGANALYTICSRESULT_LOADING = "LOGANALYTICSRESULT_LOADING";
export const FILTER_LOG_ANALYTICS_SUCCESS = "FILTER_LOG_ANALYTICS_SUCCESS";
export const FILTER_LOG_ANALYTICS_FAILED = "FILTER_LOG_ANALYTICS_FAILED";
export const GET_RANKING_DATA_SUCCESS = "GET_RANKING_DATA_SUCCESS";
export const GET_RANKING_DATA_FAILED = "GET_RANKING_DATA_FAILED";
export const GET_PIE_CHART_DATA_SUCCESS = "GET_PIE_CHART_DATA_SUCCESS";
export const GET_PIE_CHART_DATA_FAILED = "GET_PIE_CHART_DATA_FAILED";

export const GET_RESETPASSWORD_SUCCESS = "GET_RESETPASSWORD_SUCCESS";
export const GET_RESETPASSWORD_FAILED = "GET_RESETPASSWORD_FAILED";
export const SET_NEW_PASSWORD_SUCCESS = "SET_NEW_PASSWORD_SUCCESS";
export const SET_NEW_PASSWORD_FAILED = "SET_NEW_PASSWORD_FAILED";
export const SET_TOAST = "SET_TOAST";
export const SET_ERROR = "SET_ERROR";
export const RESET_EXAM_MESSAGE = "RESET_EXAM_MESSAGE";

//quizpack
export const QUIZPACK_LOADING = "QUIZPACK_LOADING";
export const QUIZPACKINDEX_LOADING = "QUIZPACKINDEX_LOADING";
export const GET_QUIZPACK_SUCCESS = "GET_QUIZPACK_SUCCESS";
export const GET_QUIZPACKINDEX_SUCCESS = "GET_QUIZPACKINDEX_SUCCESS";
export const GET_QUIZPACK_FAILED = "GET_QUIZPACK_FAILED";
export const GET_QUIZPACKINDEX_FAILED = "GET_QUIZPACKINDEX_FAILED";
export const ADD_QUIZPACK_SUCCESS = "ADD_QUIZPACK_SUCCESS";
export const ADD_QUIZPACK_FAILED = "ADD_QUIZPACK_FAILED";
export const UPDATE_QUIZPACK_SUCCESS = "UPDATE_QUIZPACK_SUCCESS";
export const UPDATE_QUIZPACK_FAILED = "UPDATE_QUIZPACK_FAILED";
export const DELETE_QUIZPACK_SUCCESS = "DELETE_QUIZPACK_SUCCESS";
export const DELETE_QUIZPACK_FAILED = "DELETE_QUIZPACK_FAILED";
export const SET_QUIZPACK_MESSAGE = "SET_QUIZPACK_MESSAGE";
export const RESET_QUIZPACK_MESSAGE = "RESET_QUIZPACK_MESSAGE";
export const GET_SINGLE_QUIZPACK_SUCCESS = "GET_SINGLE_QUIZPACK_SUCCESS";
export const GET_SINGLE_QUIZPACK_FAILED = "GET_SINGLE_QUIZPACK_FAILED";

//quiz
export const QUIZ_LOADING = "QUIZ_LOADING";
export const GET_QUIZ_SUCCESS = "GET_QUIZ_SUCCESS";
export const GET_QUIZ_FAILED = "GET_QUIZ_FAILED";
export const ADD_QUIZ_SUCCESS = "ADD_QUIZ_SUCCESS";
export const ADD_QUIZ_FAILED = "ADD_QUIZ_FAILED";
export const UPDATE_QUIZ_SUCCESS = "UPDATE_QUIZ_SUCCESS";
export const UPDATE_QUIZ_FAILED = "UPDATE_QUIZ_FAILED";
export const DELETE_QUIZ_SUCCESS = "DELETE_QUIZ_SUCCESS";
export const DELETE_QUIZ_FAILED = "DELETE_QUIZ_FAILED";
export const SET_QUIZ_MESSAGE = "SET_QUIZ_MESSAGE";
export const RESET_QUIZ_MESSAGE = "RESET_QUIZ_MESSAGE";
export const GET_SINGLE_QUIZ_SUCCESS = "GET_SINGLE_QUIZ_SUCCESS";
export const GET_SINGLE_QUIZ_FAILED = "GET_SINGLE_QUIZ_FAILED";

//lib user
export const LIB_USER_LOADING = "LIB_USER_LOADING";
export const GET_LIB_USER_SUCCESS = "GET_LIB_USER_SUCCESS";
export const GET_LIB_USER_FAILED = "GET_LIB_USER_FAILED";

//STETHO lib
export const AUSCULAIDE_LIBRARY_LOADING = "AUSCULAIDE_LIBRARY_LOADING";
export const GET_AUSCULAIDE_LIBRARY_SUCCESS = "GET_AUSCULAIDE_LIBRARY_SUCCESS";
export const GET_AUSCULAIDE_LIBRARY_FAILED = "GET_AUSCULAIDE_LIBRARY_FAILED";
export const ADD_AUSCULAIDE_FAILED = "ADD_AUSCULAIDE_FAILED";
export const ADD_AUSCULAIDE_SUCCESS = "ADD_AUSCULAIDE_SUCCESS";
export const RESET_AUSCULAIDE_MESSAGE = "RESET_AUSCULAIDE_MESSAGE";
export const UPDATE_AUSCULAIDE_SUCCESS = "UPDATE_AUSCULAIDE_SUCCESS";
export const UPDATE_AUSCULAIDE_FAILED = "UPDATE_AUSCULAIDE_FAILED";
export const DELETE_AUSCULAIDE_SUCCESS = "DELETE_AUSCULAIDE_SUCCESS";
export const DELETE_AUSCULAIDE_FAILED = "DELETE_AUSCULAIDE_FAILED";
export const SET_AUSCULIADE_MESSAGE = "SET_AUSCULIADE_MESSAGE";
export const AUSCULAIDE_USER_LOADING = "AUSCULAIDE_USER_LOADING";
export const GET_AUSCULAIDE_USER_SUCCESS = "GET_AUSCULAIDE_USER_SUCCESS";
export const GET_AUSCULAIDE_USER_FAILED = "GET_AUSCULAIDE_USER_FAILED";

//ECG lib
export const ECG_LIBRARY_LOADING = "ECG_LIBRARY_LOADING";
export const GET_ECG_LIBRARY_SUCCESS = "GET_ECG_LIBRARY_SUCCESS";
export const GET_ECG_LIBRARY_FAILED = "GET_ECG_LIBRARY_FAILED";
export const ADD_ECG_FAILED = "ADD_ECG_FAILED";
export const ADD_ECG_SUCCESS = "ADD_ECG_SUCCESS";
export const RESET_ECG_MESSAGE = "RESET_ECG_MESSAGE";
export const UPDATE_ECG_SUCCESS = "UPDATE_ECG_SUCCESS";
export const UPDATE_ECG_FAILED = "UPDATE_ECG_FAILED";
export const DELETE_ECG_SUCCESS = "DELETE_ECG_SUCCESS";
export const DELETE_ECG_FAILED = "DELETE_ECG_FAILED";
export const SET_ECG_MESSAGE = "SET_ECG_MESSAGE";

// Xray Library
export const XRAY_LIBRARY_LOADING = "XRAY_LIBRARY_LOADING";
export const GET_XRAY_LIBRARY_SUCCESS = "GET_XRAY_LIBRARY_SUCCESS";
export const GET_XRAY_LIBRARY_FAILED = "GET_XRAY_LIBRARY_FAILED";
export const ADD_XRAY_FAILED = "ADD_XRAY_FAILED";
export const ADD_XRAY_SUCCESS = "ADD_XRAY_SUCCESS";
export const UPDATE_XRAY_SUCCESS = "UPDATE_XRAY_SUCCESS";
export const UPDATE_XRAY_FAILED = "UPDATE_XRAY_FAILED";
export const DELETE_XRAY_SUCCESS = "DELETE_XRAY_SUCCESS";
export const DELETE_XRAY_FAILED = "DELETE_XRAY_FAILED";
export const SET_XRAY_MESSAGE = "SET_XRAY_MESSAGE";
export const RESET_XRAY_MESSAGE = "RESET_XRAY_MESSAGE";

//STETHO lib
export const STETHO_LIBRARY_LOADING = "STETHO_LIBRARY_LOADING";
export const GET_STETHO_LIBRARY_SUCCESS = "GET_STETHO_LIBRARY_SUCCESS";
export const GET_STETHO_LIBRARY_FAILED = "GET_STETHO_LIBRARY_FAILED";
export const ADD_STETHO_FAILED = "ADD_STETHO_FAILED";
export const ADD_STETHO_SUCCESS = "ADD_STETHO_SUCCESS";
export const RESET_STETHO_MESSAGE = "RESET_STETHO_MESSAGE";
export const UPDATE_STETHO_SUCCESS = "UPDATE_STETHO_SUCCESS";
export const UPDATE_STETHO_FAILED = "UPDATE_STETHO_FAILED";
export const DELETE_STETHO_SUCCESS = "DELETE_STETHO_SUCCESS";
export const DELETE_STETHO_FAILED = "DELETE_STETHO_FAILED";
export const SET_STETHO_MESSAGE = "SET_STETHO_MESSAGE";
export const STETHO_USER_LOADING = "STETHO_USER_LOADING";
export const GET_STETHO_USER_SUCCESS = "GET_STETHO_USER_SUCCESS";
export const GET_STETHO_USER_FAILED = "GET_STETHO_USER_FAILED";

//Inspection Library
export const INSPECTION_LIBRARY_LOADING = "INSPECTION_LIBRARY_LOADING";
export const GET_INSPECTION_LIBRARY_SUCCESS = "GET_INSPECTION_LIBRARY_SUCCESS";
export const GET_INSPECTION_LIBRARY_FAILED = "GET_INSPECTION_LIBRARY_FAILED";
export const ADD_INSPECTION_SUCCESS = "ADD_INSPECTION_SUCCESS";
export const ADD_INSPECTION_FAILED = "ADD_INSPECTION_FAILED";
export const SET_INSPECTION_MESSAGE = "SET_INSPECTION_MESSAGE";
export const DELETE_INSPECTION_LIBRARY_SUCCESS =
  "DELETE_INSPECTION_LIBRARY_SUCCESS";
export const DELETE_INSPECTION_LIBRARY_FAILED =
  "DELETE_INSPECTION_LIBRARY_FAILED";
export const UPDATE_INSPECTION_SUCCESS = "UPDATE_INSPECTION_SUCCESS";
export const UPDATE_INSPECTION_FAILED = "UPDATE_INSPECTION_FAILED";
export const RESET_INSPECTION_MESSAGE = "RESET_INSPECTION_MESSAGE";
export const RESET_INSPECTION_SUCCESS = "RESET_INSPECTION_SUCCESS";

//Palpation Library
export const PALPATION_LIBRARY_LOADING = "PALPATION_LIBRARY_LOADING";
export const GET_PALPATION_LIBRARY_SUCCESS = "GET_PALPATION_LIBRARY_SUCCESS";
export const GET_PALPATION_LIBRARY_FAILED = "GET_PALPATION_LIBRARY_FAILED";
export const ADD_PALPATION_LIBRARY_SUCCESS = "ADD_PALPATION_LIBRARY_SUCCESS";
export const ADD_PALPATION_LIBRARY_FAILED = "ADD_PALPATION_LIBRARY_FAILED";
export const SET_PALPATION_MESSAGE = "SET_PALPATION_MESSAGE";
export const RESET_PALPATION_MESSAGE = "RESET_PALPATION_MESSAGE";
export const UPDATE_PALPATION_SUCCESS = "UPDATE_PALPATION_SUCCESS";
export const UPDATE_PALPATION_FAILED = "UPDATE_PALPATION_FAILED";
export const DELETE_PALPATION_SUCCESS = "DELETE_PALPATION_SUCCESS";
export const DELETE_PALPATION_FAILED = "DELETE_PALPATION_FAILED";

//QUIZZES
export const GET_ALL_QUIZZES_SUCCESS = "GET_ALL_QUIZZES_SUCCESS";
export const GET_ALL_QUIZZES_FAILED = "GET_ALL_QUIZZES_FAILED";

// UCG Library
export const UCG_LIBRARY_LOADING = "UCG_LIBRARY_LOADING";
export const GET_UCG_LIBRARY_SUCCESS = "GET_UCG_LIBRARY_SUCCESS";
export const GET_UCG_LIBRARY_FAILED = "GET_UCG_LIBRARY_FAILED";
export const ADD_UCG_LIBRARY_SUCCESS = "ADD_UCG_LIBRARY_SUCCESS";
export const ADD_UCG_LIBRARY_FAILED = "ADD_UCG_LIBRARY_FAILED";
export const RESET_UCG_MESSAGE = "RESET_UCG_MESSAGE";
export const UPDATE_UCG_SUCCESS = "UPDATE_UCG_SUCCESS";
export const UPDATE_UCG_FAILED = "UPDATE_UCG_FAILED";
export const DELETE_UCG_SUCCESS = "DELETE_UCG_SUCCESS";
export const DELETE_UCG_FAILED = "DELETE_UCG_FAILED";
export const SET_UCG_MESSAGE = "SET_UCG_MESSAGE";

// Sort table
export const GET_SORT_TABLE_SUCCESS = "GET_SORT_TABLE_SUCCESS";
export const UPDATE_SORT_TABLE_SUCCESS = "UPDATE_SORT_TABLE_SUCCESS";
export const GET_SORT_TABLE_FAILED = "GET_SORT_TABLE_FAILED";
export const UPDATE_SORT_TABLE_FAILED = "UPDATE_SORT_TABLE_FAILED";
export const USER_SORT_TABLE_LOADING = "USER_SORT_TABLE_LOADING";

// User enable disable
export const SET_USER_DISABLED_SUCCESS = "SET_USER_DISABLED_SUCCESS";
export const SET_USER_DISABLED_FAILED = "SET_USER_DISABLED_FAILED";

// Change Password
export const CHANGE_PASSWORD_LOADING = "CHANGE_PASSWORD_LOADING";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAILED = "CHANGE_PASSWORD_FAILED";
export const SET_CHANGE_PASSWORD_MESSAGE = "SET_CHANGE_PASSWORD_MESSAGE";

export const GET_LOGANALYTICSRESULT_SUCCESS_N =
  "GET_LOGANALYTICSRESULT_SUCCESS_N";
export const GET_LOGANALYTICSRESULT_FAILED_N =
  "GET_LOGANALYTICSRESULT_FAILED_N";
export const LOGANALYTICSRESULT_LOADING_N = "LOGANALYTICSRESULT_LOADING_N";

//Select Menu
export const GET_SELECT_MENU_LOADING = "GET_SELECT_MENU_LOADING";
export const GET_SELECT_MENU_SUCCESS = "GET_SELECT_MENU_SUCCESS";
export const GET_SELECT_MENU_FAILED = "GET_SELECT_MENU_FAILED";

//Home
export const HOME_LOADING = "HOME_LOADING";
export const GET_HOME_SUCCESS = "GET_HOME_SUCCESS";
export const GET_HOME_FAILED = "GET_HOME_FAILED";
export const SET_HOME_MESSAGE = "SET_HOME_MESSAGE";
export const RESET_HOME_MESSAGE = "RESET_HOME_MESSAGE";