<?php

// resources/lang/en/nl_003.php

return [
    'elephant' => 'Kikuzo',
    'title' => 'The basics of physical assessment: Lung auscultation',
    'kenji' => 'Mr. Shoji Kudo',
    'description' => 'Public interest foundation tuberculosis prevention society Chairman <br> Nippon Medical School emeritus professor <br>',
    'desc_subtitle' => 'Basics of physical assessment <br> Lung auscultation ',
    'paragraph_1' => 'Lung auscultation, brought on by Laennec in France in the early 19th century, has been used as a basis for physical assessment in todays medical practice, 200 years ago. <br> For over a hundred years since Laennec, lung auscultation has been conveyed by text and folklore, despite being sound. <br> Paul Forgacs of the United Kingdom turned lung auscultation into science. He published a book in 1978 called "Lung Sounds", which linked the sound of lung auscultation to the respiratory physiology of the time and proposed a new science of lung sound research. In this context, in 1976, Prof. Robert Loudon and Prof. Raymond Murphy of the United States established the International Lung Sounds Association (ILSA), and have been working with the international societies every year for more than 40 years. It has been held in various places. <br> The Lung Sound (Respiratory Sound) Study Group was established in Japan in 1983 and has been held every year until today. ',
    'subtitle_1' => 'No diagnostic device is as good as a stethoscope',
    'paragraph_2' => 'Pulmonary auscultation, which has been around for more than 200 years, will never go away. A stethoscope is as simple as a stethoscope, does not burden the patient, and there is no diagnostic device that can be a communication tool with the patient. In particular, lung sounds targeted by lung auscultation, unlike heart sounds, change every moment depending on the patients respiratory condition, so the role of a stethoscope is very important. ',
    'subtitle_2' => 'Pulmonary auscultation is important in children',
    'paragraph_3' => 'In children, there are various limitations in performing diagnostic imaging such as chest x-ray, CT, MRI, and various lung function tests compared to adults. For example, it is difficult for infants up to about 3 years of age to hold their breath in the deep inhalation position, and X-ray images that can be read under certain conditions cannot be obtained. During crying, most of the time is the expiration time, and it is very difficult to shoot at the end of inspiration. Because the structure of the whole lung is finer than in an adult, the output of the image naturally declines. In order to take CT or MRI, you need to take some risks to sleep with sedatives, and even if you do so, you can only obtain images of continuous breathing, which is important for diagnostic imaging of adults In comparison, detailed observation is more difficult. Children are said to be highly radiation sensitive and more careful attention must be paid to x-ray exposure. <br> Even in the case of lung auscultation, it is difficult to cry and it is not possible to have you take a deep breath as instructed, as with other tests. However, a lung auscultation is harmless if it fails, so it can be done over and over again. It is thought that breathing sounds are generally easier to hear in children than in adults because the body is small and the distance from the airway where lung sounds are generated to the chest wall is short and it is difficult to attenuate. Furthermore, since the respiratory muscles are underdeveloped, the low frequency generated by the respiratory muscles during respiratory exercise is weak, and it is considered that the masking effect by the low frequency sound is unlikely to appear. ',
    'subtitle_3' => 'What is a good stethoscope',
    'paragraph_4' => 'Lung sounds are only a few microns vibrating on the chest wall. In order to faithfully convey this vibration as sound to the ear, it is necessary to select a stethoscope that has good sensitivity and is less likely to receive external noise. Here are the points for choosing a stethoscope. ',
    'subtitle_4' => '(a)',
    'paragraph_5' => 'You can actually hear the sound and hear it well without external noise. ',
    'method_1' => '(b)',
    'method_2' => 'After converting the chest piece several times into a membrane type and a bell type, no rattling can be felt. If there is rattling, the sensitivity is reduced and external sounds are likely to enter. ',
    'method_3' => '(c)',
    'paragraph_6' => 'The conduit is not too long. If its too long, the conduit will hit the patient and your body, clothing, and arms, picking up noise. As a guide, the chest piece should be close to your "navel" when you put the stethoscope on your ear. ',
    'image_caption' => '(d)',
    'btn_text' => 'The size of the earpiece is right for your ear. If the earpiece does not fit your ears and there is a small gap, the sensitivity will decrease significantly and noise contamination will increase. ',
    'subtitle_5' => 'Evolving auscultation materials',
    'paragraph_7' => 'The first material to "listen" to sound was recorded material from the 1960s. It replaced cassette tapes in the 70s and became CDs in the 90s. <br> These are all records of "sound" and have evolved with the times. <br> Simulators are used in recent auscultation education. Simulators are auscultation training devices that have been developed with a focus on the sound-producing side (speakers) and are being used around the world. <br> Recently, a teaching material speaker "Kikuzo" for auscultation that plays auscultation sound has been developed. This speaker is a dedicated speaker that emits body sounds, and it is a device that can reproduce lung sounds realistically while being handy. Sound sources are managed in the cloud. The auscultation portal site contains a large number of breath sounds and side noises. I think that it is a unique teaching material that allows you to learn lung auscultation anytime if you have a terminal such as a PC or smartphone that can connect to the Internet. ',
    'a1' => 'Back Number',
    'a2' => 'Back Number'
];

?>