<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Password Reset Language Lines
    |--------------------------------------------------------------------------
    |
    | The following language lines are the default lines which match reasons
    | that are given by the password broker for a password update attempt
    | has failed, such as for an invalid token or invalid new password.
    |
    */

    'password' => 'Passwords must be at least six characters and match the confirmation.',
    'reset' => 'Your password has been reset!',
    'sent' => 'We have e-mailed your password reset link!',
    'token' => 'This password reset token is invalid.',
    'user' => "We can't find a user with that e-mail address.",
    'empty' => 'Email Address is required.',
    'valid_email' => "Please enter a valid email address.",


    'title' => 'Password Reissue',
    'label' => 'Please enter your e-mail address',
    'btn' => 'Next',

    //reset password

    'pass_reset' => 'Password Reset',
    'new_pass' => 'New Password',
    'confirm_pass' => 'Confirm New Password',
    'btn_done' => 'Done',

    //alert

    'h2' => 'It has been sent',
    'p1' => 'A link has been sent to reset your password.',
    'p2' => 'Tap the link to reset your password.',

    //forgotpassword email

    'subject' => 'Reset Password',
    'content1' => 'Thank you for using "Kikuzosound.com".<br><br>
                    We have been received a request for a password reset from you.<br><br>
                    Please click the URL below to complete the procedure.<br><br>',
    'content2' => '*This e-mail is auto-generated by the system to a customer who has registered for "Kikuzosound.com" in response to a password reset request.',
    'content3' => 'If this e-mail reached you unexpectedly, please let us know through the below contact information.<br>
    Thank you for your understanding.',

    //change password

    'required' => 'Please set any password.',
    'confirmation' => 'Please confirm your password.',
    'match' => 'Passwords must match.',
    'user_not_activated' => 'Your account is not yet activated.'


];
