<?php

// resources/lang/en/reapply_browser.php

return [

    'title' => 'We will send you an e-mail to re-apply your browser',
    'note' => '<p>* You can reset the registered browser only once within 30days after your registration</p>
                <p>* In case of conflict with the regulation, the license key for browser reset will not be issued.</p>
                <p>* If you do not receive the browser re-send email, <a href="/contact"> please contact us here. </a></p>',
    'label' => 'Enter the email address linked to your account',
    'btn_text' => 'Apply',
    'alert_title' => 'You have applied for a browser reapplication.',
    'alert_link1' => 'Please check the registered e-mail address for information on re-applying your browser.',
    'text_1' => 'You can reset the registered browser only once within 3month after your registration.<br><br>
                In case of conflict with the regulation, the license key for browser reset will not be issued.',
    'alert_link2' => 'If you have any questions, please contact us here.',
    'sent' => 'We have e-mailed you the reapplication of your browser',
    'user' => "We can't find a user with that e-mail address.",
    'empty' => "Email Address is required",


    'email_subject' => 'We have accepted the re-application for the browser.',
    'email_reapply_content1' => 'Thank you for using "Kikuzosound.com".<br><br>
                        We have received your re-application for the browser.<br><br>
                        Please access from the link below and log in.<br><br>',
    'email_reapply_content2' =>'You can reset the registered browser only once within 30 days after your registration.<br><br>
                        In case of conflict with the regulation, the license key for browser reset will not be issued.<br><br>
                        * This e-mail is auto-generated by the system to a customer who has registered for "Kikuzosound.com" in response to the application of browser reset. <br>
                        If this e-mail reached you unexpectedly, please let us know through the below contact information.
                        <br>Thank you for your understanding.<br><br>',
    'user_reset_date' => 'We do not accept changes within 30 days from the previous time.'
    
];
