<?php

// resources/lang/en/messages.php

return [
    'h1' => 'Registration of "Kikuzo"',
    'p1' => '・ Register to the Kikuzo.',
    'p2' => '・ If you have purchased "Kikuzo" but have not registered, you can use "Kikuzo Library", "Quiz", etc.',
    's1' => 'Content that requires login cannot be viewed',
    'p3' => '. Be sure to register after purchase.',
    'p4' => '・ The serial number of "Kikuzo" is required for registration. Please prepare the serial number of the “Kikuzo” you purchased. The serial number can be found on the back of the product or on the back of the product box.',
    'p5' => '・ Please register all serial numbers if you have purchased multiple units.',
    'p6' => '・ After registration, you will be issued a login account and will be contacted at the e-mail address you entered.',
    'p7' => '・ Registration may take a few days due to confirmation. Please note.',
    'a1' => 'Register',
    'success_alert' => 'I applied for certification registration. After registration, we will contact you by email. Please wait for a little while.',
    'failed_alert' =>'Transmission failed. Please contact us by email to "3sp@telemedica.co.jp".',

    //email contents after registration
    'subject' => 'Registration complete',
    'content' => 'Thank you for using "Kikuzosound.com".<br><br>
    You have successfully registered a new account. <br><br>
    Please click the URL below to get started.<br><br>',
    'content2' => '* This e-mail is auto-generated by the system to a customer who has registered for "Kikuzosound.com". If this e-mail reached you unexpectedly, please let us know through the below contact information.
                     <br>Thank you for your understanding.<br><br>',


    //registration details
    'subject_detail' => '【Certification application】',
    'corp_name' => '【Corporate (facility) name】',
    'name' => '【Customer name】',
    'user_id' => '【USER ID】',
    'cust_email' => '【Email address】',
    'password' => '【Password】',
    'onetimepass' => '【One-time Password】',
    'dealer' => '【Sales company name】',
    'contact' => '【Name of person in charge】',
    'distr_email' => '【Distributor Email Address】',
    'phone_num' => '【Phone Number】',

    //email verification

    'email_activated' => 'This e-mail account is already activated',
    'resend_email_title' => 'Re-sending the verification e-mail',
    'activation_expired' => 'Account verification is not available',
    'resend_email_text' => 'In case of verification e-mail had not reached to you, you can request re-sending it.<br>
        Please input your registered e-mail address and click "Next".<br>
        * Please check your spam setting and make sure<br>
        that you can receive an e-mail from "kikuzosound@telemedica.co.jp".',
    'resend_reenter' => 'Please enter your e-mail address',
    'email_not_found' => 'We can\'t find your e-mail address, <br>
        Please register on the registration page',
    'next' => 'Next',
    'go_to_registration' => 'Go to Registration page',
    
];
