<?php

// resources/lang/ja/registration_email.php

return [
    'p1' => 'Thank you for using "Kikuzosound.com".
    <br><br>
    Your account has been registered to us.
    <br>
    To make your account active please proceed next step with the below URL and registered browser.
    <br><br>
    <p style="padding-left: 20px">&bull; You can use our service with only the browser which you used for registration.</p>
    <br>
    ----------
    <br>
    Your registered browser is:',
    'p2' => 'Please copy it and paste it in the search window of the registered browser.',
    'p3' => '*This e-mail is auto-generated by the system to a customer who has registered for "Kikuzosound.com" in response to account registration.
    <br><br>
    If this-email reached you unexpectedly, please let us know through the below contact information.
    <br>
    Thank you for your understanding.',
];